### PR TITLE
OAEP encoding

### PR DESCRIPTION
**Pull request by duncanhoggan**
The base code is in and, not sure what the testing structure is here. @stevenroose if you guys are happy pull it in.

Will PR a change to the README.MD when its in.

### CODE REVIEW

**Comment by stevenroose** [comment]
I think the README change could be part of this PR.

@lionlin @AquaWolf please review and test

**Comment by duncanhoggan** [comment]
@stevenroose readme done.

**Review by rondluper — CHANGES_REQUESTED** [review]
Thanks for this, I am just now working on a project where OAEP is really required!
Hopefully this gets added to the master branch soon.

That said, I did encounter some issues when trying to use the encryption result from this in another application.
Not sure how this kind of recommendations are generally done but here is what I did to get this working:

added `SHA1Digest().doFinal(defHash, 0);` the `OAEPEncoding `constructor

changed `hashBuf = _arraycopy(hashBuf, 0, mask, counter * hashBuf.length, hashBuf.length);` to `mask = _arraycopy(hashBuf, 0, mask, counter * hashBuf.length, hashBuf.length);` in `_maskGeneratorFunction1`

and changed `while (counter < (length / hashBuf.length))` to `while (counter < (length / hashBuf.length).floor())` in `_maskGeneratorFunction1`

**Comment by duncanhoggan** [comment]
@rondluper Will assess and check those changes and get them in.

**Comment by AquaWolf** [comment]
Sorry for the late reply didn't have that much time to test. I can't do more review for this PR because my crypto knowledge is limited. For my usecase the OAEP encoding is working. Thank you @duncanhoggan

**Comment by stevenroose** [comment]
@rondluper can you please review @duncanhoggan's last changes?

@lionlin @AquaWolf, could you also take a look perhaps?

thanks!

**Comment by AquaWolf** [comment]
Hi @stevenroose I've made a small encrypt/decrypt roundtrip with the same keypair and different frameworks. For encrypting I've used the updated implementation of @duncanhoggan then i decrypted the chiphertext with pycryptodome in python. The output of pycryptodome was the same plaintext like i had before.

**Comment by stevenroose** [comment]
@AquaWolf Did you also try the other way around?

**Comment by stevenroose** [comment]
I'm gonna merge this. Thanks a lot!

**Pull request merged**
