### PR TITLE
Migrate from bignum.BigInteger to core.BigInt

### PR DESCRIPTION
**Pull request by stevenroose**
Dart 2.0 has a native big integer type `BigInt`.  Migrate away from the
BigInteger class from the bignum package that used to be the default
implementation of big integers.

Progress is currently blocked on https://github.com/dart-lang/sdk/issues/32803. (Prefer not to implement custom methods for that because I think they make sense to exist in BigInt themselves so I suspect they will land eventually.)

Solves #121.

### CODE REVIEW

**Comment by KickedDroid** [comment]
So this should work with dart 2?
Flutter as well?

**Comment by stevenroose** [comment]
It's marked WIP. It's blocked on missing methods in the BigInt API.

I plan to implement these as util methods in PointyCastly this weekend. Will post here when it's finished and pushed and will upload to pub so that it should work with Dart 2!

**Comment by stevenroose** [comment]
This is quite finished. It seems to introduce a bug in the rsa_key_signer. The test runs indefinitely. I've been trying to debug it for a long time, but couldn't find it.

I'm a bit hesitant to merge it and especially to upload this to pub.

**Comment by KickedDroid** [comment]
That's great! Would RSA have anything to do with ed25519?

**Comment by AIDXNZ** [comment]
Here is the repo I am referencing [](https://github.com/semolex/ed25519_dart)

**Comment by KickedDroid** [comment]
Here's the repo I am referencing https://github.com/semolex/ed25519_dart

**Comment by stevenroose** [comment]
Good news! It looks like it might be this bug: https://github.com/dart-lang/sdk/issues/32626

When I was looking at it, the modPow method is always the one that is running when I pause the execution in debug mode. It's an expensive one, so I just assumed it got stuck in the for-loop where the modPow was in. I ported that part from the bignum package, so I assumed I made a mistake there.

I took a leap of *unfaith* and checked if there might be a problem with the `modPow` method. Let's wait until that change lands and see if it resolves the bug!

**Comment by stevenroose** [comment]
I'm gonna merge this because I'm getting a lot of inquiries about Dart 2 support.

Please note that there is still an unsolved issue with the RSAKeyGenerator test. I'll create an issue for that to track it.

**Comment by mathieujobin** [comment]
I see how this is very recent; Thank you for this

**Pull request merged**
