### PR TITLE
bump `reflectable` version to ^1.0.0

### PR DESCRIPTION
**Pull request by johnpryan**

### CODE REVIEW

**Comment by stevenroose** [comment]
Great! Will test and merge today. 

BTW, once configurable imports are merged into Dart, I'll rewrite the Registry again to get rid of reflectable.

**Comment by johnpryan** [comment]
Sounds good.  I'm not familiar with the differences between reflectable <1.0.0 and >=1.0.0, but things seem to be working in my project.

**Comment by stevenroose** [comment]
@johnpryan Do you use the registry, or do you directly instantiate classes by importing single files? Do you work from the browser or in the VM?

**Comment by johnpryan** [comment]
> Do you use the registry, or do you directly instantiate classes by importing single files? 
In my app, I'm importing the entire library via `import 'package:pointycastle/pointycastle.dart';` 

> Do you work from the browser or in the VM?
browser, primarily.  I haven't checked the output size so I will do that.

**Comment by johnpryan** [comment]
It looks like the output size of my application increases by about 1MB when I import `pointycastle`

**Comment by johnpryan** [comment]
I'll give a better update once the application is using the `reflectable` transformer properly.

**Comment by johnpryan** [comment]
I'm importing the library via the `package:pointycastle/pointycastle.dart` file.  The app is running in the browser - it's a polymer.dart app.   Long story short - this is hard for me to verify that `reflectable` is doing the correct thing since the `polymer.dart` transformer is running the `reflectable` transformer behind-the-scenes.

**Comment by stevenroose** [comment]
Should be fine. The only thing that could have changed was the capabilities in refelctable v1.0.0, so if the registry allows you to create instances in a browser, than it's fine.

**Pull request merged**
