### PR TITLE
Relicense the project

### PR DESCRIPTION
**Pull request by stevenroose**
The team of the Bouncy Castle Java and C# cryptography library offered to take over maintainership of this project and they would like to relicense the code under their Bouncy Castle license. Both myself and Ivan Zaera agree with the take-over by Bouncy Castle, which we'd like to kickstart by relicensing the code. Next step will be to move the code under the Bouncy Castle repositories.

It seems that we need ACKs from all copyright holders of code in the repo. I'm gonna discount contributions that were README (given that it will be replaced with Bouncy Castle's) and minor changes/bug fixes.

So we'd need
- [x] @stevenroose (PGP in commit)
- [x] @izaera (PGP in commit)
- [x] @yshrsmz (ACK'ed)
- [x] @paulreimer 
- [x] @jminer 
- [x] @GreenAppers

### CODE REVIEW

**Comment by stevenroose** [comment]
@izaera can you somehow confirm this your agreement here?

@paulreimer and @yshrsmz also have > 10 commits. While I don't think we need their consent to do this, it wouldn't hurt :) Could you guys perhaps ACK?

**Comment by yshrsmz** [comment]
:+1:

**Comment by izaera** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA256

I, Ivan Zaera, contributor of the Pointy Castle Dart
cryptography library, agree to the relicensing of the 
library to the Bouncy Castle license as of 
November 26, 2019.

-----BEGIN PGP SIGNATURE-----

iQIzBAEBCAAdFiEEZrIH3geY3wETl4wH3fnmPiqdKoAFAl3dSVcACgkQ3fnmPiqd
KoBBig/+OgOYpW1Az8yzhNSlr0n6/YsNh9ghkvl2j/ZqCiboh65MeHfBhRfuCNyP
mpObhFVnIJenBQQNr8JjrVTZ9poIH+jJYHe1Ku3u2fzFOzYYZ5rfD8IfyhpV3oJE
99UUoUecZlfAMrCqZzeeR+q5LwIHyHEk6a/sLWiWAFDXbzO19Yg3BsxeVK0y1Dab
E5WTfdrz537MDccVCoqeMQ8IYjKNlPyOl4ujlNCEcxzSRgVbYGDjqWl89h0fYYVg
vhMiUkY3Bc/jfTKnj0sownFLtgF45uylgejIY1Vkl+kD8VOWtDDEy9jXepBvjW7t
wOMTFkPhCS2Du0u+LkKhtj9H1/nFjdpO/DW4MI+08SWDoq06KcCIbGjt0r6VH9au
IHO77Nwbmly/CLJrrD+qDcAv7WlW+iUdD1Ffhgc1OFkX11aaiS7bvoIUi3URhlC6
L1XsHJM728DUf38rmjQAuYW+FckUoGFsF1Ob5fWkJNXewH/AUxaDXODH1X/rbUX4
WDqYGNZy7tPEe4XRtWh7TfXFcXCNWHncr+ERoQRI7Ne0fWUx4D8E91GHwC0iWTsB
c9TEabhbqEiRNlE4qrPPzcLC3oeqJln059z+JpaYljlHY2QkQc0a3zzYtAAlyXwA
udVBfGSTSO0Y4+f9QPUhPTa9JnwuHjwanHKh0vVyzYqZTZvc5EY=
=xNhV
-----END PGP SIGNATURE-----

**Comment by izaera** [comment]
@stevenroose :point_up:

**Comment by stevenroose** [comment]
Updated the commit to include your message as well. I think this should be sufficient. I'll wait for tomorrow to merge.

**Comment by stevenroose** [comment]
@jminer Could you also ACK since you wrote the Blake2b code that will remain in the repo?

And perhaps @GreenAppers since you added the SHA3 code.

I checked all other contributors was mostly small fixes that are probably not worthy of a copyright claim.

**Comment by GreenAppers** [comment]
👍

**Comment by jminer** [comment]
I agree to relicense under the Bouncy Castle license.

**Comment by paulreimer** [comment]
I agree to relicense under the Bouncy Castle license.

**Comment by stevenroose** [comment]
Awesome, thanks guys! Merging this.

**Pull request merged**
